(defpackage 2024-day-20
  (:use :cl :iterate :cl-ppcre :metabang-bind :trivia :trivia.ppcre)
  (:shadowing-import-from :arrow-macros :->>))
(in-package 2024-day-20)
(neat-lambda:enable-lambda-syntax)
(currying:enable-currying-syntax)

(defun read-problem ()
  (with-open-file (f (asdf:system-relative-pathname :advent-of-code-2024 "src/2024-day-20.in"))
    (labels ((recur ()
               (bind ((line (read-line f nil nil)))
                 (when line
                   (cons line (recur))))))
      (map 'vector #'identity (recur)))))

(defun grid-distance (grid start end)
  (bind ((dists (make-hash-table :test #'equal))
         (seen (make-hash-table :test #'equal))
         (xs (queues:make-queue :simple-queue))
         (directions (list #c(1 0) #c(-1 0) #c(0 1) #c(0 -1)))
         (y-bound (length grid))
         (x-bound (length (aref grid 0))))
    (labels ((in-bounds (c)
               (and (>= (realpart c) 0)
                    (>= (imagpart c) 0)
                    (< (realpart c) x-bound)
                    (< (imagpart c) y-bound)))
             (grid-get (c)
               (aref (aref grid (imagpart c))
                     (realpart c))))
      (setf (gethash start dists) 0)
      (queues:qpush xs start)
      (iter outer
        (for x = (queues:qpop xs))
        (for dist = (gethash x dists))
        (while x)
        (iter
          (for d in directions)
          (for nx = (+ x d))
          (if (= nx end)
              (return-from outer)
              (when (and (in-bounds nx)
                         (not #1=(gethash nx seen)))
                (bind ((ns (grid-get nx)))
                  (when (not (char-equal ns #\#))
                    (setf #1# t)
                    (setf (gethash nx dists) (1+ dist))
                    (queues:qpush xs nx)))))))
      dists)))

(defun grid-race (grid start end)
  (bind ((dists (grid-distance grid start end))
         (seen (make-hash-table :test #'equal))
         (xs (queues:make-queue :simple-queue))
         (directions (list #c(1 0) #c(-1 0) #c(0 1) #c(0 -1)))
         (y-bound (length grid))
         (x-bound (length (aref grid 0))))
    (labels ((in-bounds (c)
               (and (>= (realpart c) 0)
                    (>= (imagpart c) 0)
                    (< (realpart c) x-bound)
                    (< (imagpart c) y-bound)))
             (grid-get (c)
               (aref (aref grid (imagpart c))
                     (realpart c))))
      (queues:qpush xs start)
      (iter outer
        (for x = (queues:qpop xs))
        (for dist = (gethash x dists))
        (while x)
        (iter
          (for d in directions)
          (for nx = (+ x d))
          (if (= nx end)
              (next-iteration)
              (when (and (in-bounds nx)
                         (not #1=(gethash nx seen)))
                (bind ((ns (grid-get nx)))
                  (cond
                    ((and (char-equal ns #\#)
                          (in-bounds (+ nx d))
                          (char-equal (grid-get (+ nx d)) #\#)
                          (in-bounds (+ nx d d))
                          (char-equal (grid-get (+ nx d d)) #\.))
                     (format t "2 x, nx: ~a, ~a~%" x nx)
                     (in outer (counting (>= (- (gethash (+ nx d d) dists) dist) 2))))
                    ((and (char-equal ns #\#)
                          (in-bounds (+ nx d))
                          (char-equal (grid-get (+ nx d)) #\.))
                     (format t "1 x, nx: ~a, ~a~%" x nx)
                     (in outer (counting (>= (- (gethash (+ nx d) dists) dist) 2))))
                    ((char-equal ns #\.)
                     (progn
                       (setf (gethash nx seen) t)
                       (queues:qpush xs nx))))))))))))

(defun find-square (grid square)
  (iter outer
    (for y from 0 below (length grid))
    (for row in-vector grid)
    (iter
      (for x from 0 below (length row))
      (for s in-string row)
      (when (char-equal s square)
        (return-from outer (complex x y))))))

(defun part-1 ()
  (bind ((grid (read-problem))
         (start (find-square grid #\S))
         (end (find-square grid #\E)))
    (grid-race grid start end)))

;; wrong: 13718
